Iter13
firesworder/devopsmetrics pull request #15
Opened 2023-04-18 10:41 UTC by firesworder

2023-04-19 21:34 UTC, tmvrus requested changes
Работа хорошая, но у меня есть одно принципиальное замечание: в отличии от остальных хранилищ база данных умеет работать с контекстом запроса, эту возможность следует использовать.

2023-04-19 21:34 UTC, tmvrus commented on internal/server/server.go
> +		return
лишние return, ни на что не влияют

2023-04-19 21:34 UTC, tmvrus commented on internal/server/server.go
> +	writer.Write([]byte("[]"))
судя по коду, ничего такого не требуется
https://github.com/Yandex-Practicum/go-autotests/blob/main/cmd/devopstest/iteration12_test.go#L257-L270

2023-04-19 21:34 UTC, tmvrus commented on internal/storage/sql_storage.go
> +	return
большого смысла в этом нет, поскольку pgx умеет делать вот так:
```
Automatic statement preparation and caching
```

2023-04-19 21:34 UTC, tmvrus commented on internal/storage/sql_storage.go
> +func (db *SQLStorage) GetAll() (result map[string]Metric) {
эта ф-я никто не возвращает ошибку, хотя они в ней случаются

2023-04-20 10:30 UTC, firesworder commented on internal/server/server.go
> +	writer.Write([]byte("[]"))
https://github.com/Yandex-Practicum/go-autotests/blob/main/cmd/devopstest/iteration12_test.go#L254
Вот эта строчка, она пытается заполнить `var result []Metrics` и если прислать пустое тело ответа - падает ошибка парсинга

2023-04-22 10:42 UTC, firesworder commented
По одному замечанию отписался в комментарии, остальное исправил

2023-04-24 08:40 UTC, tmvrus approved these changes

2023-04-25 10:22 UTC, merged